# Generated by Django 6.0.3 on 2026-04-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
