# Generated by Django 6.0.3 on 2026-04-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
